### ISSUE TITLE
[Feature request]Universal Random Structures in 2D

### ISSUE THREAD

**Issue by junpenglao** [neozhaoliang/pywonderland#15]
Hi there,
Really nice animations and super cool project! I am wondering if there is any plan to add _Universal Random Structures in 2D_ (work by Scott Sheffield and Jason Miller). This [Quanta article](https://www.quantamagazine.org/a-unified-theory-of-randomness-20160802) gives some good introduction, and there are more demo images here: http://statslab.cam.ac.uk/~jpm205/images.html

**Comment by neozhaoliang** [comment]
@junpenglao  Yes I have always been fascinated by random structures like percolation theory, SLE curves, Ising models, square ice, etc. I have written some scripts about these topics, but I did not include them here because they are not so appealing in appearance for non-mathematicians to enjoy, and I think I'm not an expert in this field that can explain the math precisely. Also I have a bunch of projects to implement on my list (mostly about Escher's art, Coxeter group and hyperbolic geometry), so I'm afraid currently I don't have enough time to look at those random things. But **you are welcomed to propose PRs that add these features**. You should also add some explanations that why those features are mathematically beautiful, because the goal of this repo is to show the beauty of math by code.

**Comment by junpenglao** [comment]
Thanks @neozhaoliang - i will try to dig into the code and send a PR at some point.
