### ISSUE TITLE
Create a Contributing and Code of Conduct file 

### ISSUE THREAD

**Issue by Jacksole** [neozhaoliang/pywonderland#22]
I figured that this could help the overall project

**Comment by Jacksole** [comment]
Review Pull Request 21 and 22

**Comment by neozhaoliang** [comment]
Thanks for the PR. I'm very glad if other people would post their code about math visualizations here, but since this repo is created (~2 years ago) I haven't seen any PR that contributes to the `src/` to add new features to the math part. I understand this because this is a math-heavy project and there are not much people interested in doing this. I don't hope much for other people to join in this in the future, so the "contributors" and "code conduct" md files might just work only for myself?  Also as I know some  people make great math programs with poor code, so maybe they dont't care stuff about code conductions~~

**Comment by Jacksole** [comment]
Gotcha figured I try to help in someway, since. I'm not working on the source code.
